### ISSUE TITLE
Example is obsolete

### ISSUE THREAD

**Issue by UBX-FAE-ALEL** [u-blox/mbed-examples-odin-w2-mbed-3#1]
git clone https://github.com/u-blox/ublox-odin-w2-lwip-adapt.git

does not work because you need to get the the tag V2.0.1

I needed to do a checkout afterward: 
git checkout tags/v2.0.1

**Comment by asifrizwanubx** [comment]
yes, I have update module.json for next release.

**Comment by asifrizwanubx** [comment]
We will update the documentation soon.

**Comment by AmmadRehmat** [comment]
@UBX-FAE-ALEL  Is this issue still present?
